---
- name: Allocate AWS EC2
  hosts: localhost
  connection: local
  gather_facts: false
  user: ubuntu
  pre_tasks:
  - include_vars: ec2_vars/{{type}}.yml
  tasks:
  - name: Create a new security group
    ec2_group:
      name: "{{security_group_name}}"
      description: A security group created for EC2 via ansible
      vpc_id: "{{vpc_id}}"
      region: "{{aws_region}}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: basic_firewall

  - name: Create an EC2 instance
    local_action:
      module: ec2
      key_name: "{{key_name}}"
      group_id: "{{basic_firewall.group_id}}"
      instance_type: "{{ec2_instance_type}}"
      image: "{{ami_id}}"
      vpc_subnet_id: "{{subnet_ids|random}}"
      region: "{{aws_region}}"
      instance_tags: '{"Name": "{{ec2_tag_Name}}", "Type": "{{ec2_tag_Type}}", "Environment":"{{ec2_tag_Environment}}"}'
      assign_public_ip: yes
      wait: yes
      count: 1
    register: ec2

  - debug: var=item
    with_items: "{{ec2.instances}}"
  
  - add_host: name={{item.public_ip}} groups=created_nodes
    with_items: "{{ec2.instances}}"
  
  - name: Wait for the instances to boot by checking the ssh port
    wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
    with_items: "{{ec2.instances}}"
