---
- name: Delete EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  user: ubuntu
  pre_tasks:
  - include_vars: ec2_vars/{{type}}.yml
  tasks:
  - name: Terminating {{ec2_id}} instance in {{aws_region}}
    local_action:
      module: ec2
      region: "{{aws_region}}"
      wait: true
      instance_ids: "{{ec2_id}}"
      state: "absent"
        
  - name: Delete {{security_group_name}} security group
    ec2_group:
      name: "{{security_group_name}}"
      description: "A security group"
      region: "{{aws_region}}"
      vpc_id: "{{vpc_id}}"
      state: "absent"
